video_stream:
  #local it is int value 0 , 1 for index camera webcam
  type: remote
  stream_uri: http://192.168.0.100:5000/image_feed
#dlib or restinet
type_recognition: dlib

face_recognition:
  face_distance: euclit
  threshold: 0.24
face_data_path: data.pkl

data:
  #from_image,from_pkl
  load_data_type: from_image
  data_path: DataBase
  cache: resources/face_encode_data/dlib.pkl
  save_data: 
    save_type: pkl
  
autofaiss:
  use: True
  root_folder: autofaiss



classifier:
  # set False to set off the deep learning classifier
  use: False
  net:
    feature_dims: [128,256,128]
    dropout: [0.2,0.4]
  max_epochs: 20
  batch_size: 8
  caculumn_size: 14
sql:
  endpoint: ---.***.ap-southeast-1haha
  user: admin
  password: phuocvip1
  database: phuoc
  setup_command:
    - "CREATE TABLE IF NOT EXISTS orders (order_id INT AUTO_INCREMENT PRIMARY KEY, product_id INT, quantity INT);" 
    - "CREATE TABLE IF NOT EXISTS orders (order_id INT AUTO_INCREMENT PRIMARY KEY,  INT, quantity INT);"