stream_uri: 0
#dlib or restinet
type_recognition: dlib

face_recognition:
  face_distance: euclit
  threshold: 0.4
face_data_path: data.pkl
data:
  #from_image,from_pkl
  load_data_type: from_image
  data_path: DataBase
  save_data: 
    save_type: pkl
    
